#!/usr/bin/env sh

help () {
        cat <<EOM
Usage:
    単語の読み方を表示します。
    用法
    $ 東雲構文 調べる単語
EOM
}

if [ -n "$1" ];then
    if [ $1 = "-h" ] || [ $1 =  "--help" ]; then
        help
    else
        echo -n $1 
        echo -n の読み方知らなくてずっと
        echo -n $1
        echo って読んでた
        echo -n $1
        echo って読むのか
    fi
else
    echo 引数が空です。-hもしくは--helpで使い方を表示
fi